name: game
recipe: lamp
config:
  webroot: public
  php: 7.4

services:
  node:
    type: node
    build:
      - yarn install

tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node